// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdmuywmrswutxvkxqtxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkbXV5d21yc3d1dHh2a3hxdHh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MjE2MjEsImV4cCI6MjA2NTA5NzYyMX0.ZEqYKhv9goMsNEv7NagrmfAX2Yiz75KmMjyrEsl1HnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);